// Code generated by binclude; DO NOT EDIT.

package tutor

import (
	"github.com/lu4p/binclude"
	"time"
)

var (
	_binclude0	= []byte("FROM python:3.7-alpine\nWORKDIR /code\nENV FLASK_APP app.py\nENV FLASK_RUN_HOST 0.0.0.0\nRUN apk add --no-cache gcc musl-dev linux-headers\nCOPY requirements.txt requirements.txt\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"flask\", \"run\"]")
	_binclude1	= []byte("import time\n\nimport redis\nfrom flask import Flask\n\napp = Flask(__name__)\ncache = redis.Redis(host='redis', port=6379)\n\n\ndef get_hit_count():\n    retries = 5\n    while True:\n        try:\n            return cache.incr('hits')\n        except redis.exceptions.ConnectionError as exc:\n            if retries == 0:\n                raise exc\n            retries -= 1\n            time.sleep(0.5)\n\n\n@app.route('/')\ndef hello():\n    count = get_hit_count()\n    return 'Hello World! I have been seen {} times.\\n'.format(count)")
	_binclude2	= []byte("version: \"3\"\nservices:\n  web:\n    build: \"\"\n    ports:\n      - \"5000:5000\"\n  redis:\n    image: \"redis:alpine\"\n")
	_binclude3	= []byte("flask\nredis")
	BinFS		= &binclude.FileSystem{Files: map[string]*binclude.File{"../examples": {Filename: "examples", Mode: 2147484141, ModTime: time.Unix(1593357756, 336765904), Compression: binclude.None, Content: nil}, "../examples/compose": {Filename: "compose", Mode: 2147484141, ModTime: time.Unix(1593183709, 740392057), Compression: binclude.None, Content: nil}, "../examples/compose/lesson2": {Filename: "lesson2", Mode: 2147484141, ModTime: time.Unix(1593370861, 194931212), Compression: binclude.None, Content: nil}, "../examples/compose/lesson2/Dockerfile": {Filename: "Dockerfile", Mode: 420, ModTime: time.Unix(1593183709, 740595924), Compression: binclude.None, Content: _binclude0}, "../examples/compose/lesson2/app.py": {Filename: "app.py", Mode: 420, ModTime: time.Unix(1593370806, 74188581), Compression: binclude.None, Content: _binclude1}, "../examples/compose/lesson2/docker-compose.yml": {Filename: "docker-compose.yml", Mode: 420, ModTime: time.Unix(1593183709, 740958257), Compression: binclude.None, Content: _binclude2}, "../examples/compose/lesson2/requirements.txt": {Filename: "requirements.txt", Mode: 420, ModTime: time.Unix(1593370861, 194664665), Compression: binclude.None, Content: _binclude3}}}
)
